### ISSUE TITLE
Bouton "Ajouter un cépage" lors de l'ajout d'un vin

### ISSUE THREAD

**Issue by XxOrrorinxX** [ThomasCaud/NF17#5]
Lorsqu'on clique sur le bouton ajouter un cépage lors de l'ajout d'un vin, rien ne se produit

**Comment by ThomasCaud** [comment]
@courentin C'était sur ta task il me semble, on fait quoi on supprimer la fonctionnalité permettant d'ajouter plusieurs cépages en une seule fois?

**Comment by courentin** [comment]
à voir si on a le temps, sinon j'ajoute 4-5 champs cépages au lieu de faire un truc dynamique

**Comment by ThomasCaud** [comment]
Ouais met genre 5 champs t'embetes pas

**Comment by courentin** [comment]
Fixed in d33dc9801913c49f00a6824998393b1c2c5e051b
